version: '2'
services:
  proxy:
    image: nginx
    networks:
       default:
         aliases:
           - ddf.dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nodes/proxy/ddf.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nodes/proxy/ddf.dev.key:/etc/nginx/ddf.dev.key
      - ./nodes/proxy/ddf.dev.crt:/etc/nginx/ddf.dev.crt
      - ./nodes/proxy/key.pass:/etc/nginx/key.pass
    depends_on:
      - ddf1
  ddf1:
    image: oconnormi/ddf
