version: '2'
services:
  proxy:
    image: nginx
    networks:
       default:
         aliases:
           - ddf.dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nodes/proxy/ddf.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nodes/proxy/certs/ddf.dev.key:/etc/ssl/private/ddf.dev.key
      - ./nodes/proxy/certs/ddf.dev.crt:/etc/ssl/certs/ddf.dev.crt
      - ./nodes/proxy/certs/key.pass:/etc/ssl/private/key.pass
    depends_on:
      - ddf1
  ddf1:
    image: oconnormi/ddf
    environment:
      - DDF_HOSTNAME=ddf.dev
    volumes:
      - ./nodes/ddf/entrypoint.sh:/opt/ddf/entrypoint.sh
      - ./nodes/ddf/CertNew.sh:/opt/ddf/ddf-2.9.2/etc/certs/CertNew.sh
    entrypoint: /opt/ddf/entrypoint.sh
  ddf2:
    image: oconnormi/ddf
    environment:
      - DDF_HOSTNAME=ddf.dev
    volumes:
      - ./nodes/ddf/entrypoint.sh:/opt/ddf/entrypoint.sh
      - ./nodes/ddf/CertNew.sh:/opt/ddf/ddf-2.9.2/etc/certs/CertNew.sh
    entrypoint: /opt/ddf/entrypoint.sh
